services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        env_file:
            - ../.env

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: '0409'
            MYSQL_DATABASE: project_management_tool
        env_file:
            - ../.env

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "8000:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
